export const electricityOperators = [
  { "operator_name": "Adani Electricity", "type": "electricity", "operator_code": "ADEM", "params": [] },
  { "operator_name": "Ajmer Vidyut Vitran Nigam Limited", "type": "electricity", "operator_code": "AVVR", "params": [] },
  { "operator_name": "APDCL (Non-RAPDR) - ASSAM", "type": "electricity", "operator_code": "APDC", "params": [] },
  { "operator_name": "Assam Power Distribution Company Ltd (RAPDR)", "type": "electricity", "operator_code": "APDR", "params": [] },
  { "operator_name": "Bangalore Electricity supply company Ltd", "type": "electricity", "operator_code": "BESC", "params": [] },
  { "operator_name": "Bharatpur Electricity Services Ltd. (BESL)", "type": "electricity", "operator_code": "BESL", "params": [] },
  { "operator_name": "BEST Mumbai", "type": "electricity", "operator_code": "BEUM", "params": [] },
  { "operator_name": "Bikaner Electricity Supply Limited", "type": "electricity", "operator_code": "BKEB", "params": [] },
  { "operator_name": "BSES Rajdhani Power Limited", "type": "electricity", "operator_code": "BSRD", "params": [] },
  { "operator_name": "BSES Yamuna Power Limited", "type": "electricity", "operator_code": "BSYD", "params": [] },
  { "operator_name": "Calcutta Electric Supply Corporation Limited", "type": "electricity", "operator_code": "CESC", "params": [] },
  { "operator_name": "CESCOM - KARNATAKA", "type": "electricity", "operator_code": "CESK", "params": [] },
  { "operator_name": "Chhattisgarh State Power Distribution Company Ltd", "type": "electricity", "operator_code": "CSPD", "params": [] },
  { "operator_name": "Dakshin Gujarat Vij Company Limited", "type": "electricity", "operator_code": "DGVC", "params": [] },
  { "operator_name": "Dakshin Haryana Bijli Vitran Nigam", "type": "electricity", "operator_code": "DHBH", "params": [ "Mobile number" ] },
  { "operator_name": "Dadra and Nagar Haveli and Daman and Diu Power Distribution Corporation Limited", "type": "electricity", "operator_code": "DADE", "params": [] },
  { "operator_name": "DNH Power Distribution Company Limited", "type": "electricity", "operator_code": "DNHP", "params": [] },
  { "operator_name": "Goa Electricity Department", "type": "electricity", "operator_code": "GOED", "params": [] },
  { "operator_name": "Gulbarga Electricity Supply Company Limited", "type": "electricity", "operator_code": "GESK", "params": [] },
  { "operator_name": "Himachal Pradesh State Electricity Board Ltd", "type": "electricity", "operator_code": "HPSE", "params": [] },
  { "operator_name": "Hubli Electricity Supply Company Ltd", "type": "electricity", "operator_code": "HESK", "params": [] },
  { "operator_name": "Jaipur Vidyut Vitran Nigam", "type": "electricity", "operator_code": "JVVR", "params": [] },
  { "operator_name": "Jammu and Kashmir Power Development Department", "type": "electricity", "operator_code": "JKPD", "params": [] },
  { "operator_name": "Jamshedpur Utilities & Services (JUSCO)", "type": "electricity", "operator_code": "JUSC", "params": [] },
  { "operator_name": "Jharkhand Bijli Vitran Nigam Limited", "type": "electricity", "operator_code": "JBVN", "params": [] },
  { "operator_name": "Jodhpur Vidyut Vitran Nigam Limited", "type": "electricity", "operator_code": "JDVR", "params": [] },
  { "operator_name": "Kannan Devan Hills Plantations Company Private Limited", "type": "electricity", "operator_code": "KDHP", "params": [] },
  { "operator_name": "Kanpur Electricity Supply Company", "type": "electricity", "operator_code": "KESC", "params": [] },
  { "operator_name": "Kerala State Electricity Board Ltd", "type": "electricity", "operator_code": "KSEB", "params": [] },
  { "operator_name": "Kota Electricity Distribution Limited", "type": "electricity", "operator_code": "KEDR", "params": [] },
  { "operator_name": "Madhya Gujarat Vij Company Limited", "type": "electricity", "operator_code": "MGVG", "params": [] },
  { "operator_name": "Madhya Kshetra Vitaran (Rural) - Madhya Pradesh", "type": "electricity", "operator_code": "MKMP", "params": [] },
  { "operator_name": "Madhya Kshetra Vitaran (Urban) - Madhya Pradesh", "type": "electricity", "operator_code": "MKVU", "params": [] },
  { "operator_name": "Meghalaya Power Dist Corp Ltd", "type": "electricity", "operator_code": "MPDC", "params": [] },
  { "operator_name": "Maharashtra State Electricity Distbn Co Ltd (MSEDCL)", "type": "electricity", "operator_code": "MSEM", "params": [ "Billing Unit" ] },
  { "operator_name": "Muzaffarpur Vidyut Vitran", "type": "electricity", "operator_code": "MZVV", "params": [] },
  { "operator_name": "NESCO Utility", "type": "electricity", "operator_code": "NESO", "params": [] },
  { "operator_name": "New Delhi Municipal Council (NDMC)", "type": "electricity", "operator_code": "NDMC", "params": [] },
  { "operator_name": "Noida Power", "type": "electricity", "operator_code": "NOPN", "params": [] },
  { "operator_name": "North Bihar Power Distribution Co. Ltd", "type": "electricity", "operator_code": "NBBR", "params": [] },
  { "operator_name": "Paschim Gujarat Vij Company Limited", "type": "electricity", "operator_code": "PGVG", "params": [] },
  { "operator_name": "Paschim Kshetra Vidyut Vitaran - Madhya Pradesh", "type": "electricity", "operator_code": "PVMP", "params": [] },
  { "operator_name": "Poorv Kshetra Vitaran (Rural) - MADHYA PRADESH", "type": "electricity", "operator_code": "PKVR", "params": [] },
  { "operator_name": "Punjab State Power Corporation Limited", "type": "electricity", "operator_code": "PSPC", "params": [] },
  { "operator_name": "SNDL Power - NAGPUR", "type": "electricity", "operator_code": "SNPN", "params": [] },
  { "operator_name": "South Bihar Power Distribution Co. Ltd", "type": "electricity", "operator_code": "SBBR", "params": [] },
  { "operator_name": "Southern Power Distribution Company of Telangana Limited", "type": "electricity", "operator_code": "SPDC", "params": [] },
  { "operator_name": "Central Power Distribution Corporation Ltd. of Andhra Pradesh (APCPDCL)", "type": "electricity", "operator_code": "APCP", "params": [] },
  { "operator_name": "Northern Power Distribution Company of Telangana Limited", "type": "electricity", "operator_code": "NPDC", "params": [] },
  { "operator_name": "TP Southern Odisha Distribution Limited", "type": "electricity", "operator_code": "SOTO", "params": [] },
  { "operator_name": "Tamil Nadu Electricity Board", "type": "electricity", "operator_code": "TNEB", "params": [] },
  { "operator_name": "Tata Power - MUMBAI", "type": "electricity", "operator_code": "TAPM", "params": [] },
  { "operator_name": "Tata Power AJMER - RAJASTHAN", "type": "electricity", "operator_code": "TPAR", "params": [] },
  { "operator_name": "Tata Power Delhi Distribution Limited", "type": "electricity", "operator_code": "TAPD", "params": [] },
  { "operator_name": "Telangana Co-Operative Electric Supply Society Ltd", "type": "electricity", "operator_code": "TESS", "params": [] },
  { "operator_name": "Torrent Power Limited - Agra", "type": "electricity", "operator_code": "TPAG", "params": [] },
  { "operator_name": "Torrent Power Limited - Ahmedabad", "type": "electricity", "operator_code": "TPAH", "params": [] },
  { "operator_name": "Torrent Power Limited - Bhiwandi", "type": "electricity", "operator_code": "TPBW", "params": [] },
  { "operator_name": "Torrent Power Limited - Surat", "type": "electricity", "operator_code": "TPSR", "params": [] },
  { "operator_name": "Torrent Power Limited - Shilmumbrakalwa", "type": "electricity", "operator_code": "TPSM", "params": [] },
  { "operator_name": "TP Ajmer Distribution Ltd (TPADL)", "type": "electricity", "operator_code": "TPAD", "params": [] },
  { "operator_name": "TP Central Odisha Distribution Limited (TPCODL)", "type": "electricity", "operator_code": "TPCO", "params": [] },
  { "operator_name": "Tripura Electricity Corp Ltd", "type": "electricity", "operator_code": "TSTP", "params": [] },
  { "operator_name": "Uttar Gujarat Vij Company Limited", "type": "electricity", "operator_code": "UGVG", "params": [] },
  { "operator_name": "Uttar Haryana Bijli Vitran Nigam", "type": "electricity", "operator_code": "UHBV", "params": [ "Mobile number" ] },
  { "operator_name": "Uttarakhand Power Corporation Ltd - UPCL", "type": "electricity", "operator_code": "UPUK", "params": [] },
  { "operator_name": "UP Power Corporation Ltd - UPPCL", "type": "electricity", "operator_code": "UPCL", "params": [ "Discom" ] },
  { "operator_name": "WESCO Utility", "type": "electricity", "operator_code": "WESO", "params": [] },
  { "operator_name": "West Bengal State Electricity Distribution Company Limited", "type": "electricity", "operator_code": "WBSE", "params": [ "Mobile number" ] }
];

export const UP_DISCOMS = [
  "Agra-DVVNL", "Aligarh-DVVNL", "Ambedkar Nagar-MVVNL", "Amethi-MVVNL", "Amroha-PVVNL", "Auraiya-DVVNL", "Ayodhya-MVVNL", "Azamgarh-PUVNL", "Bagpat-PVVNL", "Bahraich-MVVNL", "Ballia-PUVNL", "Balrampur-MVVNL", "Banda-DVVNL", "Barabanki-MVVNL", "Bareilly-MVVNL", "Basti-PUVNL", "Bijnor-PVVNL", "Budaun-MVVNL", "Bulandshahr-PVVNL", "Chandauli-PUVNL", "Chitrakoot-DVVNL", "Deoria-PUVNL", "Etah-DVVNL", "Etawah-DVVNL", "Farrukhabad-DVVNL", "Fatehpur-PUVNL", "Firozabad-DVVNL", "Gautam Buddha Nagar-PVVNL", "Ghaziabad-PVVNL", "Ghazipur-PUVNL", "Gonda-MVVNL", "Gorakhpur-PUVNL", "Hamirpur-DVVNL", "Hapur District-PVVNL", "Hardoi-MVVNL", "Hathras-DVVNL", "Jalaun-DVVNL", "Jaunpur-PUVNL", "Jhansi-DVVNL", "Kannauj-DVVNL", "Kanpur Dehat-DVVNL", "Kanpur Nagar-DVVNL", "Kanpur Nagar-KESCO", "Kasganj-DVVNL", "Kaushambi-PUVNL", "Kushinagar-PUVNL", "Lakhimpur Kheri-MVVNL", "Lalitpur-DVVNL", "Lucknow-MVVNL", "Maharajganj-PUVNL", "Mahoba-DVVNL", "Mainpuri-DVVNL", "Mathura-DVVNL", "Mau-PUVNL", "Meerut-PVVNL", "Mirzapur-PUVNL", "Moradabad-PVVNL", "Muzaffarnagar-PVVNL", "Pilibhit-MVVNL", "Pratapgarh-PUVNL", "PrayagRaj-PUVNL", "Raebareli-MVVNL", "Rampur-PVVNL", "Saharanpur-PVVNL", "Sambhal-PVVNL", "Sant Kabir Nagar-PUVNL", "Sant Ravidas Nagar-Bhadohi-PUVNL", "Shahjahanpur-MVVNL", "Shamli-PVVNL", "Shravasti-MVVNL", "Siddharthnagar-PUVNL", "Sitapur-MVVNL", "Sonbhadra-PUVNL", "Sultanpur-MVVNL", "Unnao-MVVNL", "Varanasi-PUVNL"
];
